### ISSUE TITLE
The help page shows incorrect mode (hemiocta2equ)

### ISSUE THREAD

**Issue by vrpixel** [Scobalula/Aether#1]
I noticed a small error. Hemi-Octahedron To Equirectangular section shows incorrect mode, but even if I change it to hemiocta2equ and try to convert Vanguard sky to equirectangular, it seems that only left (top) side of the image is used, and the bottom half is mirrored.

![image](https://user-images.githubusercontent.com/46872885/157112593-1c81c13b-b5de-429f-8181-11e762628e73.png)

![image](https://user-images.githubusercontent.com/46872885/157112530-ae7a8ccc-7c4f-4ded-9c77-b0a6750cd6af.png)

**Comment by Scobalula** [comment]
Thanks, this should now be fixed in the latest release, along with adjusting the direction for MW/VG.
