### ISSUE TITLE
Problems with conversion

### ISSUE THREAD

**Issue by vrpixel** [Scobalula/Aether#2]
Thanks for the recent update. It fixed the original issue.
Now I'm trying to convert cubemap into equi.

![image](https://user-images.githubusercontent.com/46872885/159073004-05b4c9a1-eecc-4757-b60a-a0dcab21dcd2.png)

Using "--mode=cubearray2equ" I get actually the octa projection:

![image](https://user-images.githubusercontent.com/46872885/159073104-b58e0386-61c0-4e26-9ed8-6069d810d118.png)

Then using "hemiocta2equ" i get this a bit distorted output:
![image](https://user-images.githubusercontent.com/46872885/159073222-328bc459-1c13-4652-ac04-ed9372317c4e.png)

Also one thing I noticed, since version 1.0.0.1 the commands require full input/outputh path, but that's minor.

**Comment by Scobalula** [comment]
The shader is designed for Z upaxis used in Call of Duty, you should be able to edit the shader to adjust the view direction for different directions.
